[tool.poetry]
name = "Lightning.py"
version = "3.0.0-beta"
description = ""
authors = ["LightSage <lightsage01@gmail.com>"]
license = "AGPL-3.0-or-later"
readme = "README.md"
repository = "https://gitlab.com/lightning-bot/Lightning"

[tool.poetry.dependencies]
python = "^3.7"
"discord.py" = {git = "https://github.com/LightSage/discord.py"}
Pillow = "^7.2.0"
python-dateutil = "^2.8.1"
parsedatetime = "^2.6"
psutil = "^5.7.2"
tabulate = "^0.8.7"
uwuify = "^1.0.1"
hiredis = "^1.1.0"
aredis = "^1.1.8"
feedparser = "^5.2.1"
asyncpg = "^0.21.0"
uvloop = "^0.14.0"
discord-ext-menus = {git = "https://github.com/LightSage/discord-ext-menus"}
lru_dict = "^1.1.6"
sentry-sdk = "0.19.5"
migra = {extras = ["pg"], version = "^1.0.1597915807", optional = true}
"discord.py-stubs" = {version = "^1.4.0", optional = true}
attrs = "20.3.0"
py-flags = "^1.1.4"
jishaku = {git = "https://gitlab.com/Gorialis/jishaku.git"}
rapidfuzz = "^0.14.2"
typer = "^0.3.2"
yoyo-migrations = "^7.2.1"
psycopg2 = "^2.8.6"
tomlkit = "^0.7.0"

[tool.poetry.dev-dependencies]
isort = "^5.4.2"
flake8 = "^3.8.3"

[tool.poetry.scripts]
lightning = 'lightning.__main__'

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
